excel_headers:
- SAMPLE
- HGVS
- GENE/LOCUS
- GENE/LOCUS_DESCRIPTION
- TOTAL_LOCUS_DEPTH
- VARIANT_HETEROPLASMY
- ALT_DEPTH
- REF_DEPTH
- TOTAL_SAMPLE_DEPTH
#VARIANT_QUALITY
- TOTAL_MAPPING_QUALITY
#TIER
- COHORT COUNT
- COHORT FREQUENCY
- CHR
- POS
- REF
- ALT
- QUAL
- FILTER
#ANTICODON
- GENE
- GENE_BIOTYPE
- PHYLOTREE_MUT
- PHYLOTREE_HAPLOTYPE
- GT_FORMAT
- INFO
- FORMAT
- gnomAD_AC_homoplasmy
- gnomAD_AC_heteroplasmy
- gnomAD_AF_homoplasmy
- gnomAD_AF_heteroplasmy
- gnomAD_max_het_level
- clinvar_significance
- clinvar_status
#MGRB_FILTER
#MGRB_AN
#MGRB_AC
#MGRB_FREQUENCY
- MITOMAP_DISEASE_AC
- MITOMAP_DISEASE_AF
- MITOMAP_DISEASE_AACHANGE
- MITOMAP_DISEASE_HOMOPLASMY
- MITOMAP_DISEASE_HETEROPLASMY
- MITOMAP_DISEASE_PUBMED_IDS
- MITOMAP_DISEASE_DISEASE
- MITOMAP_DISEASE_DISEASE_STATUS
- MITOMAP_DISEASE_HGFL
- MITOMAP_CONFIRMED_MUTATIONS_LOCUS
- MITOMAP_CONFIRMED_MUTATIONS_LOCUSTYPE
- MITOMAP_CONFIRMED_DISEASE
- MITOMAP_CONFIRMED_MUTATIONS_ALLELE
- MITOMAP_CONFIRMED_MUTATIONS_AMINOACIDCHANGE
- MITOMAP_CONFIRMED_MUTATIONS_STATUSMITOMAPCLINGEN
- MITOMAP_CONFIRMED_MUTATIONS_LASTUPDATE
# MITOMAP_MUTATIONS_CODING_CONTROL_LOCUS
# MITOMAP_MUTATIONS_CODING_CONTROL_ALLELE
# MITOMAP_MUTATIONS_CODING_CONTROL_DISEASE
# MITOMAP_MUTATIONS_CODING_CONTROL_NUCLEOTIDECHANGE
- MITOMAP_MUTATIONS_CODING_CONTROL_AMINOACIDCHANGE
# MITOMAP_MUTATIONS_CODING_CONTROL_PLASMY
# MITOMAP_MUTATIONS_CODING_CONTROL_STATUS
- MITOMAP_MUTATIONS_CODING_CONTROL_GB_FREQ
- MITOMAP_MUTATIONS_CODING_CONTROL_GB_SEQS
# MITOMAP_MUTATIONS_CODING_CONTROL_REFERENCES
- MITOMAP_MUTATIONS_RNA_LOCUS
- MITOMAP_MUTATIONS_RNA_DISEASE
- MITOMAP_MUTATIONS_RNA_ALLELE
# MITOMAP_MUTATIONS_RNA_RNA
- MITOMAP_MUTATIONS_RNA_HOMOPLASMY
- MITOMAP_MUTATIONS_RNA_HETEROPLASMY
- MITOMAP_MUTATIONS_RNA_STATUS
- MITOMAP_MUTATIONS_RNA_MITOTIP
- MITOMAP_MUTATIONS_RNA_GB_FREQ
- MITOMAP_MUTATIONS_RNA_GB_SEQS
- MITOMAP_MUTATIONS_RNA_REFERENCES
- MITOMAP_POLYMORPHISMS_AC
- MITOMAP_POLYMORPHISMS_AF
# MITOMAP_POLYMORPHISMS_HGFL
- MITOMAP_VARIANTS_CODING_LOCUS
# MITOMAP_VARIANTS_CODING_NUCLEOTIDECHANGE
# MITOMAP_VARIANTS_CODING_CODONNUMBER
# MITOMAP_VARIANTS_CODING_CODONPOSITION
- MITOMAP_VARIANTS_CODING_AMINOACIDCHANGE
- MITOMAP_VARIANTS_CODING_GB_FREQ
- MITOMAP_VARIANTS_CODING_GB_SEQS
- MITOMAP_VARIANTS_CODING_CURATEDREFERENCES
# MITOMAP_VARIANTS_CONTROL_LOCUS
# MITOMAP_VARIANTS_CONTROL_NUCLEOTIDECHANGE
- MITOMAP_VARIANTS_CONTROL_GB_FREQ
- MITOMAP_VARIANTS_CONTROL_GB_SEQS
- MITOMAP_VARIANTS_CONTROL_CURATEDREFERENCES
- MITOTIP_SCORE
# MITOTIP_PERCENTILE
# MITOTIP_QUARTILE
- MITOTIP_SCORE_INTERPRETATION
# MITOMAP_MITOTIP_STATUS
# MITOTIP_COUNT
# MITOTIP_PERCENTAGE
vcf_headers:
  annotations:
    #ANTICODON: ANTICODON
    GENE: GENE
    GENE_BIOTYPE: GENE_BIOTYPE
    PHYLOTREE_MUT: PHYLOTREE_MUT
    PHYLOTREE_HAPLOTYPE: PHYLOTREE_HAPLOTYPE
    #MGRB_FILTER: MGRB_FILTER
    #MGRB_AN: MGRB_AN
    #MGRB_AC: MGRB_AC
    #MGRB_FREQUENCY: MGRB_FREQUENCY
    MITOMAP_DISEASE_AC: MITOMAP_DISEASE_AC
    MITOMAP_DISEASE_AF: MITOMAP_DISEASE_AF
    MITOMAP_DISEASE_AACHANGE: MITOMAP_DISEASE_AACHANGE
    MITOMAP_DISEASE_HOMOPLASMY: MITOMAP_DISEASE_HOMOPLASMY
    MITOMAP_DISEASE_HETEROPLASMY: MITOMAP_DISEASE_HETEROPLASMY
    MITOMAP_DISEASE_PUBMED_IDS: MITOMAP_DISEASE_PUBMED_IDS
    MITOMAP_DISEASE_DISEASE: MITOMAP_DISEASE_DISEASE
    MITOMAP_DISEASE_DISEASE_STATUS: MITOMAP_DISEASE_DISEASE_STATUS
    MITOMAP_DISEASE_HGFL: MITOMAP_DISEASE_HGFL
    MITOMAP_CONFIRMED_MUTATIONS_LOCUS: MITOMAP_CONFIRMED_MUTATIONS_LOCUS
    MITOMAP_CONFIRMED_MUTATIONS_LOCUSTYPE: MITOMAP_CONFIRMED_MUTATIONS_LOCUSTYPE
    MITOMAP_CONFIRMED_MUTATIONS_ASSOCIATEDDISEASE: MITOMAP_CONFIRMED_DISEASE
    MITOMAP_CONFIRMED_MUTATIONS_ALLELE: MITOMAP_CONFIRMED_MUTATIONS_ALLELE
    MITOMAP_CONFIRMED_MUTATIONS_AMINOACIDCHANGE: MITOMAP_CONFIRMED_MUTATIONS_AMINOACIDCHANGE
    MITOMAP_CONFIRMED_MUTATIONS_STATUSMITOMAPCLINGEN: MITOMAP_CONFIRMED_MUTATIONS_STATUSMITOMAPCLINGEN
    MITOMAP_CONFIRMED_MUTATIONS_LASTUPDATE: MITOMAP_CONFIRMED_MUTATIONS_LASTUPDATE
    #MITOMAP_MUTATIONS_CODING_CONTROL_LOCUS: MITOMAP_MUTATIONS_CODING_CONTROL_LOCUS
    #MITOMAP_MUTATIONS_CODING_CONTROL_ALLELE: MITOMAP_MUTATIONS_CODING_CONTROL_ALLELE
    #MITOMAP_MUTATIONS_CODING_CONTROL_DISEASE: MITOMAP_MUTATIONS_CODING_CONTROL_DISEASE
    #MITOMAP_MUTATIONS_CODING_CONTROL_NUCLEOTIDECHANGE: MITOMAP_MUTATIONS_CODING_CONTROL_NUCLEOTIDECHANGE
    MITOMAP_MUTATIONS_CODING_CONTROL_AMINOACIDCHANGE: MITOMAP_MUTATIONS_CODING_CONTROL_AMINOACIDCHANGE
    #MITOMAP_MUTATIONS_CODING_CONTROL_PLASMY: MITOMAP_MUTATIONS_CODING_CONTROL_PLASMY
    #MITOMAP_MUTATIONS_CODING_CONTROL_STATUS: MITOMAP_MUTATIONS_CODING_CONTROL_STATUS
    MITOMAP_MUTATIONS_CODING_CONTROL_GB_FREQ: MITOMAP_MUTATIONS_CODING_CONTROL_GB_FREQ
    MITOMAP_MUTATIONS_CODING_CONTROL_GB_SEQS: MITOMAP_MUTATIONS_CODING_CONTROL_GB_SEQS
    #MITOMAP_MUTATIONS_CODING_CONTROL_REFERENCES: MITOMAP_MUTATIONS_CODING_CONTROL_REFERENCES
    MITOMAP_MUTATIONS_RNA_LOCUS: MITOMAP_MUTATIONS_RNA_LOCUS
    MITOMAP_MUTATIONS_RNA_DISEASE: MITOMAP_MUTATIONS_RNA_DISEASE
    MITOMAP_MUTATIONS_RNA_ALLELE: MITOMAP_MUTATIONS_RNA_ALLELE
    #MITOMAP_MUTATIONS_RNA_RNA: MITOMAP_MUTATIONS_RNA_RNA
    MITOMAP_MUTATIONS_RNA_HOMOPLASMY: MITOMAP_MUTATIONS_RNA_HOMOPLASMY
    MITOMAP_MUTATIONS_RNA_HETEROPLASMY: MITOMAP_MUTATIONS_RNA_HETEROPLASMY
    MITOMAP_MUTATIONS_RNA_STATUS: MITOMAP_MUTATIONS_RNA_STATUS
    MITOMAP_MUTATIONS_RNA_MITOTIP: MITOMAP_MUTATIONS_RNA_MITOTIP
    MITOMAP_MUTATIONS_RNA_GB_FREQ: MITOMAP_MUTATIONS_RNA_GB_FREQ
    MITOMAP_MUTATIONS_RNA_GB_SEQS: MITOMAP_MUTATIONS_RNA_GB_SEQS
    MITOMAP_MUTATIONS_RNA_REFERENCES: MITOMAP_MUTATIONS_RNA_REFERENCES
    MITOMAP_POLYMORPHISMS_AC: MITOMAP_POLYMORPHISMS_AC
    MITOMAP_POLYMORPHISMS_AF: MITOMAP_POLYMORPHISMS_AF
    #MITOMAP_POLYMORPHISMS_HGFL: MITOMAP_POLYMORPHISMS_HGFL
    MITOMAP_VARIANTS_CODING_LOCUS: MITOMAP_VARIANTS_CODING_LOCUS
    #MITOMAP_VARIANTS_CODING_NUCLEOTIDECHANGE: MITOMAP_VARIANTS_CODING_NUCLEOTIDECHANGE
    #MITOMAP_VARIANTS_CODING_CODONNUMBER: MITOMAP_VARIANTS_CODING_CODONNUMBER
    #MITOMAP_VARIANTS_CODING_CODONPOSITION: MITOMAP_VARIANTS_CODING_CODONPOSITION
    MITOMAP_VARIANTS_CODING_AMINOACIDCHANGE: MITOMAP_VARIANTS_CODING_AMINOACIDCHANGE
    MITOMAP_VARIANTS_CODING_GB_FREQ: MITOMAP_VARIANTS_CODING_GB_FREQ
    MITOMAP_VARIANTS_CODING_GB_SEQS: MITOMAP_VARIANTS_CODING_GB_SEQS
    MITOMAP_VARIANTS_CODING_CURATEDREFERENCES: MITOMAP_VARIANTS_CODING_CURATEDREFERENCES
    #MITOMAP_VARIANTS_CONTROL_LOCUS: MITOMAP_VARIANTS_CONTROL_LOCUS
    #MITOMAP_VARIANTS_CONTROL_NUCLEOTIDECHANGE: MITOMAP_VARIANTS_CONTROL_NUCLEOTIDECHANGE
    MITOMAP_VARIANTS_CONTROL_GB_FREQ: MITOMAP_VARIANTS_CONTROL_GB_FREQ
    MITOMAP_VARIANTS_CONTROL_GB_SEQS: MITOMAP_VARIANTS_CONTROL_GB_SEQS
    MITOMAP_VARIANTS_CONTROL_CURATEDREFERENCES: MITOMAP_VARIANTS_CONTROL_CURATEDREFERENCES
    MITOTIP_SCORE: MITOTIP_SCORE
    #MITOTIP_PERCENTILE: MITOTIP_PERCENTILE
    #MITOTIP_QUARTILE: MITOTIP_QUARTILE
    MITOTIP_SCORE_INTERPRETATION: MITOTIP_SCORE_INTERPRETATION
    #MITOMAP_STATUS: MITOMAP_MITOTIP_STATUS
    #COUNT: MITOTIP_COUNT
    #PERCENTAGE: MITOTIP_PERCENTAGE
    gnomAD_AC_hom: gnomAD_AC_homoplasmy
    gnomAD_AC_het: gnomAD_AC_heteroplasmy
    gnomAD_AF_hom: gnomAD_AF_homoplasmy
    gnomAD_AF_het: gnomAD_AF_heteroplasmy
    gnomAD_max_hl: gnomAD_max_het_level
    clinvar_pathogenic: clinvar_significance
    clinvar_status: clinvar_status
  format:
    AD[0]: REF_DEPTH
    AD[1]: ALT_DEPTH
    DP: TOTAL_SAMPLE_DEPTH
    GT: GT_FORMAT
    AF: VARIANT_HETEROPLASMY
    #q: VARIANT_QUALITY
    #tier: TIER
  info:
    DP: TOTAL_LOCUS_DEPTH
    MQ: TOTAL_MAPPING_QUALITY
    MAP_LOCUS_DESCRIPTION: GENE/LOCUS_DESCRIPTION
    MAP_LOCUS: GENE/LOCUS
    